### PR TITLE
Replace deprecated pep8 package with pycodestyle

### PR DESCRIPTION
**Pull request by jdavidheiser**
fix for issue #30, where the pep8 package doesn't work with parsing python files on stdin anymore.

### CODE REVIEW

**Comment by twolfson** [comment]
It looks like `flake8` wants us to request the logical lines as our plugin. Can you explore this venue instead?

http://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html

**Comment by jdavidheiser** [comment]
Most other flake8 plugins aren't using the tree yet, and to be honest I don't have the time to restructure the logic of the project.  This simple fix works for the time being, and is at least on par with how other plugins are still doing it.

**Comment by twolfson** [comment]
Could you link us to these other plugins?

**Comment by xZise** [comment]
Apart from that it should either import `pep8` or `pycodestyle`, because if you installed `flake8` before the name change, this would break it.

**Comment by xZise** [comment]
Okay I did a few tests and xZise/flake8-quotes@cc444c5 is using the import from `flake8` itself, which is `pycodestyle` on newer versions (like 2.6.2). This is fixing the issue I reported in #30 and it correctly checks the input. But when I rebase it on top #34 and use it with 3.0.0b2 it doesn't work because the read string from `stdin` is empty.

So I'm not sure how we can go forward here. Either it doesn't support 3.x using `stdin`, or there is some kind of backport (`FileProcessor` I guess?) which makes the basic `stdin` handling available to Flake8 2.x.

**Comment by twolfson** [comment]
I don't understand how #34 would break it if it works in `3.x`. Fwiw, if you read directly from `stdin` (e.g. `sys.stdin.read()`) it will be empty as `flake8` has already consumed all the bytes into memory.

**Comment by xZise** [comment]
Okay sorry for the spam, but I think I figured it out and will provide one (or maybe two) pull requests.

On Flake8 3.x we could actually use a custom constructor which directly gets us the lines, so the plugin doesn't need the pep8 magic. As it should support 2.x the pep8 magic would still be there but only run on 3.x. This is actually using `FileProcessor` (any parameter in the constructor is filled with the data from the attribute with the same name in `FileProcessor`) so in theory we could also use the tokens. I'll take a look into it.

The implementation I got was to have one base class and two subclasses depending on the Flake8 version. One just gets the lines (or tokens, and because of [Flake8 bug 159](https://gitlab.com/pycqa/flake8/issues/159) also `tree` but that isn't used). And the other subclass does the same as the current one as it reads from `stdin` or the file system and writes it into the lines (just as the 3.x version).

Additionally I figured out why on Flake8 the errors didn't show up (for me at least) as the errors aren't selected by default (and thus ignored). I'm not sure if this intentional or a bug and maybe I'll report a bug about that.

**Comment by twolfson** [comment]
I don't understand why we would want to work around the simple interface that `pep8` provides. Can you elaborate?

**Comment by xZise** [comment]
Didn't saw the new comment. #34 doesn't directly breaks it, but that enables this plugin to be used in 3.x. And there Flake8 seems to do it differently and consumes `stdin` before `pycodestyle` got to it, and when the plugin requests the `stdin` from `pycodestyle` it got nothing. It is possible to get the `stdin` from `flake8` though, but that isn't available in Flake8 2.x. I can provide three commits shortly:

1. The commit fixing the `stdin` issue in Flake8 2.x, but this won't work with Flake8 3.x. (xZise/flake8-quotes@cc444c5)
2. A commit using `flake8.utils.get_stdin_value` instead of `pep8.get_stdin_value` which fixes the issue mentioned in this comment.
3. A commit with the two classes mentioned in my previous comment.

Now regarding your new comment why I would want to work around pep8:

1. This is a plugin of Flake8 not pep8, so I think it shouldn't depend on pep8, especially as Flake8 3.x seems to have gotten more independent. Not sure if the long goal for Flake8 is to be independent of pep8 which is then just another plugin.
2. Apart from being a Flake8 plugin, not relying on pep8 prevents this issue in the first place. There would be no need to switch from pep8 to pycodestyle. Does pip uninstall pep8 when you update this plugin?
3. As mentioned here, we can't use it with Flake8 3.x. At least I couldn't find an easy way.
4. Additionally Flake8 3.x provides an even simpler interface (although because we need to support Flake8 2.x it isn't as simple as it could be).

**Comment by twolfson** [comment]
Everything sounds good except for the 2 classes; those seem like overkill. How about something like:

```python
pep8.stdin_get_value().splitlines(True) || sys.stdin.read() || ''
```

**Comment by xZise** [comment]
So I uploaded all the different commits. I disagree that the two classes are overkill, especially as they avoid to use pep8 or any stdin special logic in Flake8 3.x. Please take a look at the commit to check whether it is still overkill.

Anyway in Flake8 3.x your suggestion won't work because `sys.stdin.read()` is also empty:
```
$ echo 'f = "foobar"' | flake8 - --select=Q
''
```

There I modified `get_file_contents`:

    def get_file_contents(self):
        if self.filename in ('stdin', '-', None):
            s = sys.stdin.read()
            print(repr(s))
            return s.splitlines(True)
        else:
            return pep8.readlines(self.filename)

**Comment by twolfson** [comment]
Ah, I misinterpretted "It is possible to get the stdin from flake8 though, but that isn't available in Flake8 2.x.". I thought you meant `stdin.read()` worked as expected in `Flake8@3.x` whereas we had to use `get_file_contents()` prior.

**Comment by twolfson** [comment]
After reading into it a bit more, I understand why we need 2 classes; `flake8` is doing parameter sniffing. Can you open a PR so we can start commenting on the code directly? I have some feedback but it's complex to give here.

**Comment by xZise** [comment]
I think this patch should work similar to tk0miya/flake8-coding@70ba7ae and still import pep8 if pycodestyle couldn't be imported (aka used on an old install where Flake8 still uses pep8).

**Comment by twolfson** [comment]
Closing this issue for now as explained in https://github.com/zheller/flake8-quotes/issues/30#issuecomment-231320109

**Comment by xZise** [comment]
After my initial “bashing” it would be possible to use this patch instead of #38. Especially as #38 uses `from flake8.engine import pep8`, which seems not the way to go apparently.

The main changes I'd like to see:
* Import `pep8` as a fallback
* Maybe depend on `flake8` instead of `pep8`, because then it's probably going to use the import Flake8 is using (although you could install Flake8 <2.6 and separately pycodestyle in which case it'd use pycodestyle not pep8)

And maybe the last point isn't really solvable and in which case using Flake8's import is actually the better idea.

**Pull request closed without merging**
