### PR TITLE
avoid flake8 warning

### PR DESCRIPTION
**Pull request by dirk-thomas**
```WARNING:flake8.processor:Plugin requested optional parameter "builtins" but this is not an available parameter.```

### CODE REVIEW

**Comment by twolfson** [comment]
Hm, I could have sworn that was a valid parameter at some point. Any idea when `flake8` removed support for that `kwarg`?

**Comment by dirk-thomas** [comment]
This seems to be the change in question: https://github.com/PyCQA/flake8/commit/2d3e277b1e0c0a24c30c611558692f95d14a8470

**Comment by twolfson** [comment]
Thanks for the link! It looks like that was over a year old so I think this is safe to land. Landing shortly :shipit:

**Comment by twolfson** [comment]
This has been merged/released in `0.12.0`. Thanks for the PR!

**Comment by dirk-thomas** [comment]
Thank you for the quick merge & release :+1:

**Pull request merged**
