### PR TITLE
Prefer flake8-provided lines over parsing file

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by skirpichev** [comment]
@twolfson, I don't sure why the status check wasn't displayed (pr was created as a draft, maybe), but tests are [ok](https://travis-ci.org/github/zheller/flake8-quotes/builds/666911629?utm_medium=notification&utm_source=github_status)

**Comment by twolfson** [comment]
Looks good to me =) Going to land this in a `major` release as our core API has changed if anyone was invoking us directly

**Comment by twolfson** [comment]
This PR has been released in `3.0.0`. Thanks for your quick back and forths and work here

**Comment by skirpichev** [comment]
In fact, I think that using self.lines should be preferred and filename argument - deprecated.  This will require, through, major changes in tests.

**Pull request merged**
