### PR TITLE
Make the error message show what kind of string is bad.

### PR DESCRIPTION
**Pull request by Julian**
Closes: #102

### CODE REVIEW

**Review by twolfson — COMMENTED** [review]
Ehh, I have a lot of nitpicks around this implementation =/ Will just commandeer rather than try to force mindreading =/ Will update + land by Fri Aug 27

- Would prefer messages be written out as-is inside the `INLINE` and `MULTILINE` configs (good for i18n flexibility)
- New messages are *very* verbose, worry about being too noisy for console feedback
- Disliking how tests are using variables in assertion expectationss (should almost always be avoided as it can lead to more levels of indirection which makes testing unclear)

**Comment by Julian** [comment]
Sure, go for it, thanks.

**Comment by twolfson** [comment]
Looking into this now. As a heads up, this branch is currently failing `./test.sh`. I'll look into why as part of the resolution

**Comment by twolfson** [comment]
That was kind of tedious but it's all back to functional now. Landing PR

**Comment by twolfson** [comment]
This has been released in `flake8-quotes@3.3.0`. Thanks for your work!

**Pull request merged**
